### ISSUE TITLE
Connect to local CosmosDB emulator

### ISSUE THREAD

**Issue by wouterroos** [hackolade/CosmosDB-with-Gremlin-API#21]
Hi,

Is there a way (or are there any plans) to connect to a local CosmosDB emulator?

Thanks!

**Comment by pdesmarets** [comment]
We have not tried it.  But I suppose that the instructions for the other APIs should apply? https://hackolade.com/help/Localinstance2.html

**Comment by pdesmarets** [comment]
What do you mean with " an issue there that seems to be related with it being a serverless instance"??  this plugin is specific to Cosmos DB on Azure, which is indeed serverless by nature.  What kind of issue?
I suggest you send requests to our helpdesk at support@hackolade.com which is a much better way to track tickets than here..  Thanks!

**Comment by wouterroos** [comment]
@pdesmarets I got an error stating that a certain api request executed by hackolade is not supported when using a serverless instance of CosmosDB. For the difference between 'provisioned throughput' and  'serverless', see https://docs.microsoft.com/en-us/azure/cosmos-db/throughput-serverless
